#pragma once

enum InputCommand
{
  CMD_NONE,

  // GLOBAL / TRANSPORT
  CMD_TRANSPORT_TOGGLE,
  CMD_MODE_TOGGLE,
  CMD_SONG_MODE_TOGGLE,
  CMD_TEST_TOGGLE,
  CMD_BPM_ENTER,
  CMD_UNDO,

  CMD_QUANTIZE_MENU,

  // NAVIGATION
  CMD_PATTERN_PREV,
  CMD_PATTERN_NEXT,
  CMD_TRACK_PREV,
  CMD_TRACK_NEXT,

  // DIRECT TRACK SELECTION (Matrix A, B, C, D)
  CMD_TRACK_1,
  CMD_TRACK_2,
  CMD_TRACK_3,
  CMD_TRACK_4,

  CMD_PLAYLIST_PREV,
  CMD_PLAYLIST_NEXT,

  // STEPS / TRIGGERS (1-16)
  CMD_TRIGGER_1,
  CMD_TRIGGER_2,
  CMD_TRIGGER_3,
  CMD_TRIGGER_4,
  CMD_TRIGGER_5,
  CMD_TRIGGER_6,
  CMD_TRIGGER_7,
  CMD_TRIGGER_8,
  CMD_TRIGGER_9,
  CMD_TRIGGER_10,
  CMD_TRIGGER_11,
  CMD_TRIGGER_12,
  CMD_TRIGGER_13,
  CMD_TRIGGER_14,
  CMD_TRIGGER_15,
  CMD_TRIGGER_16,

  // PLAYLIST EDITING
  CMD_PLAYLIST_INSERT_PREV, // Insert Duplicate Before
  CMD_PLAYLIST_INSERT_NEXT, // Insert Duplicate After
  CMD_PLAYLIST_DELETE,

  // PLAYLIST BANKS
  CMD_PLAYLIST_BANK_1,
  CMD_PLAYLIST_BANK_2,
  CMD_PLAYLIST_BANK_3,
  CMD_PLAYLIST_BANK_4,

  // CONFIRMATION MODALS
  CMD_CLEAR_PROMPT,
  CMD_CONFIRM_YES,
  CMD_CONFIRM_NO
};